default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: postgresql://localhost/wrkt_task_development?pool=5

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'postgresql://localhost/wrkt_task_test' } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { 'postgresql://localhost/wrkt_task_development?pool=5' } %>

queue:
  <<: *default

cable:
  <<: *default